project:
  type: sdca-theme

website:
  title: "PRODIAP"
  site-url: "https://steno-aarhus.github.io/prodiap/"
  repo-url: "https://github.com/steno-aarhus/prodiap"
  navbar:
    pinned: true
    left:
      - text: "Baggrund" 
        href: baggrund.qmd
      - text: "Ofte stillede spørgsmål"
        href: faq.qmd
      - text: "Kontakt"
        href: kontakt.qmd
      - text: "Web-patient support"
        href: support.qmd
    right: 
      - text: "<span class='btn btn-light role=button'>Tilmeld</span>"
        href: "https://redcap.au.dk/surveys/?s=KMCN3FHX47YNEXPN"

format: sdca-theme-html

editor: 
  markdown:
    wrap: 72
    canonical: true
