<style>
 /* Farve og styling til callout-overskrifter */
 .callout.callout-style-default .callout-header {
     background-color: rgb(153, 0, 51) !important;
     color: white !important; /* Hvid tekst */
     font-weight: bold !important;
     text-shadow: 0px 0px 2px rgba(255, 255, 255, 0.8) !important;
  padding: 10px !important;
     border-radius: 5px !important;
 }
 
 /* Fjern brun baggrund og skygger */
 .callout.callout-style-default {
     background-color: transparent !important;
     border-left: none !important;
     box-shadow: none !important;
 }
 </style>

# Ofte stillede spørgsmål

::: {.callout collapse="true"}
## Hvad går PRODIAP projektet ud på?
PRODIAP-projektet undersøger, hvordan et spørgeskema med patientrapporterede oplysninger kan understøtte årssamtalen for personer med type 2-diabetes i almen praksis. Spørgeskemaet giver et struktureret overblik over patientens behov og oplevelse af egen sygdom, hvilket kan understøtte en mere målrettet og effektiv samtale.
:::

::: {.callout collapse="true"}
## Hvilke spørgsmål indeholder PRODIAP spørgeskemaet?
Antallet af spørgsmål i PRODIAP varierer mellem 42 og 51, da nogle spørgsmåls fremkomst afhænger af svarene på de forudgående spørgsmål.

PRODIAP indeholder følgende spørgsmål:

- **SF12**: Selvrapporteret helbredsstatus (1 spørgsmål)  
- **WHO5**: Generel trivsel (5 spørgsmål)  
- **MDI**: Depressionsscreening (2 spørgsmål)
- **PAID5**: Problem Areas In Diabetes (5 spørgsmål)
- **Symptomer**: (6-11 spørgsmål)
- **Søvn**: (3 spørgsmål)
- **Undersøgelser**: (2 spørgsmål)
- **Seksualitet**: (2 spørgsmål)
- **Medicin og blodsukker**: (3-7 spørgsmål)
- **Egenomsorg**: (6 spørgsmål)
- **Diabetes-uddannelse**: (2 spørgsmål)
- **KRAM**: (4 spørgsmål)
- **Emner til samtale**: (1 spørgsmål)
:::

::: {.callout collapse="true"}
## Hvem kan deltage?
Der er plads til at ca. 30 almen praksis kan deltage i projektet i alt i Region Midtjylland, Region Syddanmark og Region Sjælland.
:::

::: {.callout collapse="true"}
## Hvornår skal vores almen praksis starte i projektet?
Vi forventer at I kan starte projektet op indenfor tre måneder fra I har tilmeldt jer projektet.
:::

::: {.callout collapse="true"}
## Hvad indebærer det at deltage?
De deltagende almen praksis bliver fordelt i en interventions- og en kontrolgruppe.
For almen praksis i **interventionsgruppen** indebærer deltagelse, at patienter med type 2-diabetes besvarer PRODIAP inden årssamtalen, og at behandlerne anvender besvarelsen som en del af samtalen. Der vil være en kort oplæringsperiode, hvor behandlerne får introduktion til PRODIAP og dets anvendelse.

For almen praksis i **kontrolgruppen** vil årssamtalen fortsætte som vanligt uden brug af PRODIAP.

**Alle** deltagende almen praksis (både i interventions- og i kontrolgruppen) skal rekruttere i gennemsnit 67 patienter til projektet, som skal besvare et baseline spørgeskema i starten af projektet og et follow-up spørgeskema som afslutning på projektet.

Derudover vil der blive gennemført interviews og observationer i udvalgte praksisser. Alle deltagende almen praksis (både i interventions- og kontrolgruppen) har mulighed for at beholde skemaet i behandelingen efter projektet er afsluttet.
:::

::: {.callout collapse="true"}
## Hvad får vores almen praksis ud af at deltage?
Deltagelse giver mulighed for at være med til at udvikle fremtidens årssamtaler og få indsigt i, hvordan patientrapporterede oplysninger kan integreres i almen praksis. Derudover bidrager projektet til ny viden om, hvordan diabetesbehandling kan målrettes patienternes behov mere effektivt.
:::
