## Information til deltagere

Du er blevet inviteret til at deltage i et nationalt forskningsprojekt gennem din lægepraksis.
Projektet udføres af Steno Diabetes Center Aarhus i samarbejde med Steno Diabetes
Center Odense og Steno Diabetes Center Sjælland.

Formålet med projektet er at undersøge, hvordan personer med type 2-diabetes oplever kvaliteten af deres behandling i almen praksis.

## Hvad indebærer deltagelse?
I projektet sammenligner vi to forskellige måder at gennemføre årssamtalen på.
Den ene er den, der allerede anvendes i almen praksis, mens den anden er en ny tilgang, hvor der anvendes et spørgeskema om livet med type 2-diabetes som en del af årsamtalen.

For at kunne sammenligne disse to måder at afholde årssamtale på, bliver alle deltagere bedt om at besvare et evalueringsspørgeskema før deres årssamtale det første år og efter årssamtalen det andet år.

Vi undersøger den oplevede kvalitet af behandlingen ved at bede dig og andre personer med type 2-diabetes
om at besvare et spørgeskema i forbindelse med årssamtalen.

Spørgeskemaet hedder Diabetes Årssamtale og indeholder spørgsmål om
velbefindende, diabetesstress, sundhedsvaner og behov for støtte.
Spørgeskemaet skal hjælpe med at gøre årssamtalen mere fokuseret på
dine behov og udfordringer.

[Se invitationen her](https://drive.google.com/file/d/1-ffilR2UMEfMudjgsFE9_RWPW1dD9Dvu/view?usp=sharing)
